[Service]
ProtectProc=invisible
ProcSubset=pid
ProtectSystem=strict
PrivateDevices=yes
DevicePolicy=closed
MountAPIVFS=yes
PrivateTmp=yes
PrivateIPC=yes
PrivatePIDs=yes
PrivateUsers=yes
NoNewPrivileges=yes
MemoryDenyWriteExecute=yes
CapabilityBoundingSet=
ProtectControlGroups=strict
ProtectHostname=yes
ProtectClock=yes
ProtectKernelTunables=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectHome=tmpfs
RestrictAddressFamilies=AF_UNIX
LockPersonality=yes
RestrictRealtime=yes
RestrictNamespaces=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallErrorNumber=EPERM
TemporaryFileSystem=/dev/shm:rw,noexec,nosuid,nodev
InaccessiblePaths=-/boot
WorkingDirectory=~
TemporaryFileSystem=%h:rw,noexec,nosuid,nodev
TemporaryFileSystem=/run:ro,noexec,nosuid,nodev
TemporaryFileSystem=/var:ro,noexec,nosuid,nodev
TemporaryFileSystem=%t:rw,noexec,nosuid,nodev
InaccessiblePaths=-/srv
InaccessiblePaths=-/opt
NoExecPaths=-+/tmp
