[Scope]
StateDirectory=%p/%i
StateDirectory=%p/%i/%j:%j
CacheDirectory=%p/%i
CacheDirectory=%p/%i/%j:%j
CacheDirectory=%p/%i/Downloads:Downloads
BindPaths=%C/%p/%i/Downloads:%h/Downloads
RuntimeDirectory=%p/%i
RuntimeDirectory=%p/%i/%j:%j
